searches:
  - name: "SW London family home"
    agent: foxtons
    areas:
      - kingston
      - raynes-park
      - wimbledon
    min_price: 600000
    max_price: 1000000
    min_bedrooms: 4
    property_types:
      - house

email:
  to: "mohit.sanwal@gmail.com"
  from: "aclaudetest23@gmail.com"
